spring:
  datasource:
    primary:
      driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://192.168.159.128:3306/mydb
      url: jdbc:mysql://192.168.11.131:3306/mydb
      username: wls
      password: Wls141215!
    secondary:
      driver-class-name: com.mysql.jdbc.Driver
  #    url: jdbc:mysql://192.168.159.128:3306/mydb
      url: jdbc:mysql://192.168.11.131:3306/shopmall
      username: wls
      password: Wls141215!
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  thymeleaf:
    mode: HTML5
    encoding: utf-8
    content-type: text/html
    cache: false
  output:
    ansi:
      enabled: always
  mvc:
    view:
      prefix: /templates/
      suffix: .*
  mail:
    host: smtp.qq.com
    username: 158822436@qq.com
    password: Wls141215sxj
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    database: 0
#    host: 192.168.159.128
    host: 192.168.11.131
    port: 6379
    password: Wls141215!
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 0
mybatis:
  type-aliases-package: com.wls.diypro.model
  mapper-locations: classpath:static/sqlmapper/*.xml
  check-config-location: true
#  config-location: classpath:mybatis/mybatis-config.xml
logging:
  level:
    com.wls.shopmall: debug


age:  18
name: 张三
content: "name: ${name}, age: ${age}"
cron: 0/3 * * * * ?
com.diy.title: 纯洁的微笑
com.diy.description: 分享生活和技术

orderInfo:
  orderNumber: 1245
  receiver: wls
  province: 北京
  city: 北京
  area: 大兴区
  street: 广平大街9号
  addressDetail:  九州通医药有限公司
  orderStatus:  1
  invoiceInfo:
      invoiceTitle: 北京好药师大药房连锁有限公司
      invoiceType: 1
  details:
    - orderDetail:
        productId:  1
        productCode:  BC001
        productName:  商品1
        unitPrice:  10.01
        count:  1
#   - orderDetail:
#        productId:  2
#        productCode:  BC002
#        productName:  商品2
#        unitPrice:  10.01
#        count:  1